python ex01-blockchain-explore.py
python ex02-blockchain-rates.py
python ex03-blockchain-stats.py
python ex04-bitcoin-wallets.py
python ex05-bitcoin-multisig.py
python ex06-coinmarketcap.py
python ex07-ethereum.py
python ex08-ethereum-matplotlib.py
python ex09-gdax.py
python ex10-gdax-refactored.py
python ex11-gdax-products.py
python ex12-gdax-orderbook.py
python ex13-gad-trades.py
python ex14-blotter.py
python ex15-blotter-pricing.py
python ex16-gdax-websockets.py
python ex17-pnl.py
python ex18-trade.py
python ex19-vwap.py